name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get timestamp
        id: vars
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --target=app --tag app:${{ env.TAG }}